kind: pipeline
type: docker
name: default

steps:
  - name: php8.1
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ord.vultrcr.com/auroradev/php-fpm-laravel
      registry: ord.vultrcr.com
      tags:
        - php8.1
    depends_on:
      - clone
  - name: php8.2
    image: plugins/docker
    settings:
      build_args:
        - PHP_VERSION=8.2
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ord.vultrcr.com/auroradev/php-fpm-laravel
      registry: ord.vultrcr.com
      tags:
        - php8.2
    depends_on:
      - clone
  - name: php8.3
    image: plugins/docker
    settings:
      build_args:
        - PHP_VERSION=8.3
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ord.vultrcr.com/auroradev/php-fpm-laravel
      registry: ord.vultrcr.com
      tags:
        - php8
        - php8.3
    depends_on:
      - clone
  - name: php8.1-caddy
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.caddy
      repo: ord.vultrcr.com/auroradev/php-fpm-laravel
      registry: ord.vultrcr.com
      tags:
        - php8.1-caddy
    depends_on:
      - php8.1
  - name: php8.2-caddy
    image: plugins/docker
    settings:
      build_args:
        - PHP_VERSION=8.2
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.caddy
      repo: ord.vultrcr.com/auroradev/php-fpm-laravel
      registry: ord.vultrcr.com
      tags:
        - php8.2-caddy
    depends_on:
      - php8.2
  - name: php8.3-caddy
    image: plugins/docker
    settings:
      build_args:
        - PHP_VERSION=8.3
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.caddy
      repo: ord.vultrcr.com/auroradev/php-fpm-laravel
      registry: ord.vultrcr.com
      tags:
        - php8-caddy
        - php8.3-caddy
    depends_on:
      - php8.3